### ISSUE TITLE
Add support for polling PgQ via LISTEN/NOTIFY

### ISSUE THREAD

**Issue by ocharles** [pgq/skytools-legacy#8]
I would to be able to write daemon's that use PgQ for messages, but would rather not have to run in an infinite loop with 'sleep' calls. Instead, I would rather block on via libpq to recieve a notification from a 'pgq' channel. I currently have a prototype of this working nicely, whereby I added the following:

``` sql
create or replace function notify_pgq_tick() returns trigger as $$ begin notify pgqticker; return null; end; $$ language plpgsql;
create trigger pgqtick after insert or update or delete on pgq.tick for each statement  execute procedure notify_pgq_tick();
```

My application can then block on notifications from the 'pgqticker' channel.

Thoughts?

**Comment by markokr** [comment]
The current logic is based on following assumptions:
- There are always new events incoming in busy database
- If there are many consumers, you don't want them all coming in at the same time.  So such random separation that the sleep() creates is good.

Could you describe why the sleep() loop is unsatisfactory for your situation?

**Comment by ocharles** [comment]
Hmm, I guess I have no real justification other than finding blocking for an event cleaner - it saves me a bit of CPU, and a bit of network activity to do the poll myself.

In terms of the first point, that doesn't apply to me (yet) because my database is very low on writes, and it's writes that currently trigger PgQ events. I can appreciate the second point, but I only have a single consumer for now, so I hadn't considered that.

That said, even having notifications doesn't mean you have to actually use them :)

**Comment by markokr** [comment]
Although the amount of code to be added on ticker side is small, it still feels wrong to optimize for idle system.

And note that it's easy change on ticker side, but it gets more complex on consumer side - how do they know whether to listen for notification or not?  And if the queue setting changes, how do they follow it?

And all consuming libraries need to be changed with the logic.

So it does seem simpler to avoid notifications, and on idle system you can simply tune timeouts to decrease the noise level.

**Comment by ocharles** [comment]
I don't have any further arguments, so I'll trust your judgement that the correct logic is for the best. Thanks for discussing this with me!
